### ISSUE TITLE
[Experiment] Axis line with incomplete expressions

### ISSUE THREAD

**Issue by edward-ji** [Quark-Games/YEquals#26]
![Screen Shot 2021-11-10 at 10 22 32 pm](https://user-images.githubusercontent.com/32563880/141104699-b73b4611-be37-4259-aed7-d56fb8222278.png)
![Screen Shot 2021-11-10 at 10 24 52 pm](https://user-images.githubusercontent.com/32563880/141104734-22ba38d3-3531-45e6-a3bf-d42a781d7e88.png)

**Comment by zwang20** [comment]
This bug has been fixed in db95ced
